close all;
load coeff.mat
        IPF = @(x)( ...
    +b(1).*x(:,1) ...  
    +b(2).*x(:,2) ...
    +b(3).*x(:,3) ...
    +b(4).*x(:,4) ...
    +b(5).*x(:,1).*x(:,1) ...
    +b(6).*x(:,2).*x(:,2) ...
    +b(7).*x(:,3).*x(:,3) ...
    +b(8).*x(:,4).*x(:,4) ...
    +b(9).*x(:,1).*x(:,2) ...
    +b(10).*x(:,1).*x(:,3) ...
    +b(11).*x(:,1).*x(:,4) ...
    +b(12).*x(:,2).*x(:,3) ...
    +b(13).*x(:,2).*x(:,4) ...
    +b(14).*x(:,3).*x(:,4) ...
    +b(15) ...
    );
        SEA = @(x)( ...
    +c(1).*x(:,1) ...  
    +c(2).*x(:,2) ...
    +c(3).*x(:,3) ...
    +c(4).*x(:,4) ...
    +c(5).*x(:,1).*x(:,1) ...
    +c(6).*x(:,2).*x(:,2) ...
    +c(7).*x(:,3).*x(:,3) ...
    +c(8).*x(:,4).*x(:,4) ...
    +c(9).*x(:,1).*x(:,2) ...
    +c(10).*x(:,1).*x(:,3) ...
    +c(11).*x(:,1).*x(:,4) ...
    +c(12).*x(:,2).*x(:,3) ...
    +c(13).*x(:,2).*x(:,4) ...
    +c(14).*x(:,3).*x(:,4) ...
    +c(15) ...
    );
        MultiObj.fun = @(x) [IPF(x) -SEA(x)];
        MultiObj.nVar = 4;
        MultiObj.var_min = [1 120 300 2];
        MultiObj.var_max = [2 160 500 5];
%end

% Parameters
params.Np = 100;        % Population size
params.pc = 0.9;        % Probability of crossover
params.pm = 0.5;        % Probability of mutation
params.maxgen = 100;     % Maximum number of generations
params.ms = 0.05;       % Mutation strength

% NSGA-II algorithm
[R,Rfit,Rrank] = NSGAII(params,MultiObj);   
row = sum(Rrank==1);
paretofront = Rfit(1:row,:);
optimalsolution = R(1:row,:);

scatter(paretofront(:,1),paretofront(:,2),'b*','LineWidth',3);
xlim([62 62.5])
ylim([-2200 -1600])