close all;
load coeff.mat
        IPF = @(x)( ...
    +d(1).*x(:,1) ...  
    +d(2).*x(:,2) ...
    +d(3).*x(:,3) ...
    +d(4).*x(:,4) ...
    +d(5).*x(:,1).*x(:,1) ...
    +d(6).*x(:,2).*x(:,2) ...
    +d(7).*x(:,3).*x(:,3) ...
    +d(8).*x(:,4).*x(:,4) ...
    +d(9).*x(:,1).*x(:,2) ...
    +d(10).*x(:,1).*x(:,3) ...
    +d(11).*x(:,1).*x(:,4) ...
    +d(12).*x(:,2).*x(:,3) ...
    +d(13).*x(:,2).*x(:,4) ...
    +d(14).*x(:,3).*x(:,4) ...
    +d(15).*x(:,1).*x(:,1).*x(:,1) ...
    +d(16).*x(:,1).*x(:,1).*x(:,2) ...
    +d(17).*x(:,1).*x(:,2).*x(:,2) ...
    +d(18).*x(:,2).*x(:,2).*x(:,2) ...
    +d(19) ...
    );
        SEA = @(x)( ...
    +e(1).*x(:,1) ...  
    +e(2).*x(:,2) ...
    +e(3).*x(:,3) ...
    +e(4).*x(:,4) ...
    +e(5).*x(:,1).*x(:,1) ...
    +e(6).*x(:,2).*x(:,2) ...
    +e(7).*x(:,3).*x(:,3) ...
    +e(8).*x(:,4).*x(:,4) ...
    +e(9).*x(:,1).*x(:,2) ...
    +e(10).*x(:,1).*x(:,3) ...
    +e(11).*x(:,1).*x(:,4) ...
    +e(12).*x(:,2).*x(:,3) ...
    +e(13).*x(:,2).*x(:,4) ...
    +e(14).*x(:,3).*x(:,4) ...
    +e(15).*x(:,1).*x(:,1).*x(:,1) ...
    +e(16).*x(:,1).*x(:,1).*x(:,2) ...
    +e(17).*x(:,1).*x(:,2).*x(:,2) ...
    +e(18).*x(:,2).*x(:,2).*x(:,2) ...
    +e(19) ...
    );
        MultiObj.fun = @(x) [IPF(x) -SEA(x)];
        MultiObj.nVar = 4;
        MultiObj.var_min = [1 100 300 2];
        MultiObj.var_max = [3 160 500 5];
%end

% Parameters
params.Np = 100;        % Population size
params.pc = 0.9;        % Probability of crossover
params.pm = 0.5;        % Probability of mutation
params.maxgen = 100;     % Maximum number of generations
params.ms = 0.05;       % Mutation strength

% NSGA-II algorithm
[R,Rfit,Rrank,fitipf,fitsea,tr,A,L,T] = NSGAII(params,MultiObj);  
row = sum(Rrank==1);
paretofront = Rfit(1:row,:);
optimalsolution = R(1:row,:);

scatter(paretofront(:,1),paretofront(:,2),'b*','LineWidth',3);
xlim([62 62.5])
ylim([-2200 -1600])